### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by janrudolf** [datom/xbmc-addons#2]
Hey datom,

looks like great work. But I didn't manage to install the tv-kino-plugin on my raspbmc. Downloaded your gitrep, made a zip out of the plugin-path, but raspbmc claims some missing depenencies. Can you help, what the plugin needs?

Thanks a lot,
Jan

**Comment by datom** [comment]
Hi Jan,

thanks for your message.
i fixed the problem. please try out the new version.

**Comment by janrudolf** [comment]
Thank you for your work - the addons seems to work pretty well now.
